title: Universal Label Template
description: A safe, adaptive JSON format for printer-independent label templates.
theme: minima
markdown: kramdown
url: https://opentlp.github.io
baseurl: /opentlp/studio/ult
exclude:
  - package.json
