/**
 * Build the OpenTLP hardware exports.
 *
 * Markdown front matter remains the source of truth. The generated runtime
 * projection is intentionally small: Studio needs names, aliases and protocol
 * families for discovery, not prose, source records or artwork.
 */

import { mkdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { loadDevices, loadFamilies, ROOT } from './lib/load.mjs';

const EXPORT_VERSION = 1;
const DIST_DIR = join(ROOT, 'dist');
const GENERATED_DIR = join(ROOT, 'generated');

const { devices: loadedDevices, errors } = await loadDevices();
const { devices: loadedFamilies, errors: familyErrors } = await loadFamilies();
errors.push(...familyErrors);

if (errors.length) {
    for (const error of errors) console.error(`error ${error}`);
    process.exit(1);
}

const devices = loadedDevices
    .map(({ device }) => device)
    .sort((a, b) => a.id.localeCompare(b.id));
const families = loadedFamilies
    .map(({ device }) => device)
    .sort((a, b) => a.id.localeCompare(b.id));
const generated = new Date().toISOString().slice(0, 10);

const deviceExport = {
    version: EXPORT_VERSION,
    generated,
    licence: 'CC0-1.0',
    count: devices.length,
    devices
};
const familyExport = {
    version: EXPORT_VERSION,
    generated,
    licence: 'CC0-1.0',
    count: families.length,
    families
};
const catalogue = {
    source: 'packages/hardware/devices',
    schemaVersion: EXPORT_VERSION,
    generated,
    licence: 'CC0-1.0',
    count: devices.length,
    devices: devices.map(device => ({
        id: device.id,
        brand: device.brand,
        model: device.model,
        aliases: [...(device.aliases ?? [])].sort((a, b) => a.localeCompare(b)),
        rebadgeOf: device.rebadge_of ?? null,
        family: device.protocol?.family ?? null,
        status: device.status ?? null
    }))
};

await rm(DIST_DIR, { recursive: true, force: true });
await rm(GENERATED_DIR, { recursive: true, force: true });
await mkdir(DIST_DIR, { recursive: true });
await mkdir(GENERATED_DIR, { recursive: true });

await writeJson(join(DIST_DIR, 'devices.json'), deviceExport);
await writeJson(join(DIST_DIR, 'families.json'), familyExport);
await writeJson(join(DIST_DIR, 'catalogue.json'), catalogue);
await writeFile(
    join(GENERATED_DIR, 'catalogue.ts'),
    `// Generated by packages/hardware/scripts/export.mjs. Do not edit.\n` +
    `export default ${JSON.stringify(catalogue, null, 2)} as const;\n`,
    'utf8'
);

console.log(`Built ${devices.length} device and ${families.length} family records.`);

async function writeJson(path, value) {
    await writeFile(path, JSON.stringify(value, null, 2) + '\n', 'utf8');
}
