/**
 * Build the OpenTLP hardware exports.
 *
 * Markdown front matter remains the source of truth. The generated runtime
 * projection is intentionally small: Studio needs names, aliases and protocol
 * families for discovery, not prose, source records or artwork.
 */

import { mkdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { loadDevices, loadFamilies, loadApps, ROOT } from './lib/load.mjs';

const EXPORT_VERSION = 1;
const DIST_DIR = join(ROOT, 'dist');
const GENERATED_DIR = join(ROOT, 'generated');

const { devices: loadedDevices, errors } = await loadDevices();
const { devices: loadedFamilies, errors: familyErrors } = await loadFamilies();
const { devices: loadedApps, errors: appErrors } = await loadApps();
errors.push(...familyErrors, ...appErrors);

if (errors.length) {
    for (const error of errors) console.error(`error ${error}`);
    process.exit(1);
}

const devices = loadedDevices
    .map(({ device }) => device)
    .sort((a, b) => a.id.localeCompare(b.id));
const families = loadedFamilies
    .map(({ device }) => device)
    .sort((a, b) => a.id.localeCompare(b.id));
const apps = loadedApps
    .map(({ device }) => device)
    .sort((a, b) => a.id.localeCompare(b.id));
const generated = new Date().toISOString().slice(0, 10);

const deviceExport = {
    version: EXPORT_VERSION,
    generated,
    licence: 'CC0-1.0',
    count: devices.length,
    devices
};
const familyExport = {
    version: EXPORT_VERSION,
    generated,
    licence: 'CC0-1.0',
    count: families.length,
    families
};
const appExport = {
    version: EXPORT_VERSION,
    generated,
    licence: 'CC0-1.0',
    count: apps.length,
    apps
};
const catalogue = {
    source: 'packages/hardware/devices',
    schemaVersion: EXPORT_VERSION,
    generated,
    licence: 'CC0-1.0',
    count: devices.length,
    devices: devices.map(device => ({
        id: device.id,
        brand: device.brand,
        model: device.model,
        aliases: [...(device.aliases ?? [])].sort((a, b) => a.localeCompare(b)),
        rebadgeOf: device.rebadge_of ?? null,
        family: device.protocol?.family ?? null,
        app: resolveApp(device),
        replacesApps: device.protocol?.replaces_apps ?? (resolveApp(device) ? [resolveApp(device)] : []),
        kind: resolveKind(device),
        status: device.status ?? null
    })),
    apps: apps.map(app => ({
        id: app.id,
        name: app.name,
        developer: app.developer,
        summary: app.summary ?? null,
        brandColor: app.brand_color,
        brandPalette: app.brand_palette,
        badgeLetter: app.badge_letter,
        platforms: app.platforms ?? {},
        protocols: app.protocols ?? [],
        replacesApps: app.replaces_apps ?? [],
        popularModels: app.popular_models ?? [],
        isMultiDevice: app.is_multi_device ?? false,
        status: app.status ?? null
    }))
};

await rm(DIST_DIR, { recursive: true, force: true });
await rm(GENERATED_DIR, { recursive: true, force: true });
await mkdir(DIST_DIR, { recursive: true });
await mkdir(GENERATED_DIR, { recursive: true });

await writeJson(join(DIST_DIR, 'devices.json'), deviceExport);
await writeJson(join(DIST_DIR, 'families.json'), familyExport);
await writeJson(join(DIST_DIR, 'apps.json'), appExport);
await writeJson(join(DIST_DIR, 'catalogue.json'), catalogue);
await writeFile(
    join(GENERATED_DIR, 'catalogue.ts'),
    `// Generated by packages/hardware/scripts/export.mjs. Do not edit.\n` +
    `export default ${JSON.stringify(catalogue, null, 2)} as const;\n`,
    'utf8'
);

console.log(`Built ${devices.length} device, ${families.length} family, and ${apps.length} app records.`);

async function writeJson(path, value) {
    await writeFile(path, JSON.stringify(value, null, 2) + '\n', 'utf8');
}

function resolveApp(device) {
    if (device.protocol?.app) return device.protocol.app;
    const vendorApp = device.protocol?.vendor_app;
    if (vendorApp) {
        if (vendorApp.includes('tinyPrint')) return 'Tiny Print';
        if (vendorApp.includes('funnyprint')) return 'Fun Print';
        if (vendorApp.includes('mxw')) return 'WalkPrint';
        if (vendorApp.includes('peripage')) return 'PeriPage';
        if (vendorApp.includes('marklife')) return 'Marklife';
        if (vendorApp.includes('niimbot') || vendorApp.includes('jcprint')) return 'NIIMBOT';
        if (vendorApp.includes('phomemo')) return 'Phomemo';
    }
    const family = device.protocol?.family;
    if (family === 'tiny') return 'Tiny Print';
    if (family === 'funny-lx') return 'Fun Print';
    if (family === 'mxw01') return 'WalkPrint';
    if (family === 'peripage') return 'PeriPage';
    if (family === 'marklife') return 'Marklife';
    if (family === 'niimbot') return 'NIIMBOT';
    return null;
}

function resolveKind(device) {
    if (device.kind) return device.kind;
    const family = device.protocol?.family;
    const media = device.print?.media;
    const widthMm = device.print?.width_mm;
    if (family === 'tiny' || family === 'funny-lx' || family === 'mxw01') return 'pocket';
    if (media?.includes('gap') || media?.includes('die-cut') || (widthMm && widthMm <= 25)) return 'label';
    if (device.id?.includes('receipt') || family === 'esc-pos') return 'receipt';
    return 'label';
}
